repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: requirements-txt-fixer
- repo: local
  hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [ python ]
      files: ^(app/|tests/)
