version: "3.8"
services:
  cron:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["crond", "-f"]
    environment:
      DEXCOM_OAUTH_CLIENT_ID: ${DEXCOM_OAUTH_CLIENT_ID}
      DEXCOM_OAUTH_CLIENT_SECRET: ${DEXCOM_OAUTH_CLIENT_SECRET}
      DEXCOM_PASSWORD: ${DEXCOM_PASSWORD}
      DEXCOM_USER: ${DEXCOM_USER}
      HUE_BRIDGE_IP: ${HUE_BRIDGE_IP}
      HUE_BRIDGE_USERNAME: ${HUE_BRIDGE_USERNAME}
      HUE_BRIDGE_CLIENT_KEY: ${HUE_BRIDGE_CLIENT_KEY}


  cgm-lights:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DEXCOM_OAUTH_CLIENT_ID: ${DEXCOM_OAUTH_CLIENT_ID}
      DEXCOM_OAUTH_CLIENT_SECRET: ${DEXCOM_OAUTH_CLIENT_SECRET}
      DEXCOM_PASSWORD: ${DEXCOM_PASSWORD}
      DEXCOM_USER: ${DEXCOM_USER}
      HUE_BRIDGE_IP: ${HUE_BRIDGE_IP}
      HUE_BRIDGE_USERNAME: ${HUE_BRIDGE_USERNAME}
      HUE_BRIDGE_CLIENT_KEY: ${HUE_BRIDGE_CLIENT_KEY}
    command: ["python","app/daemon.py"]


