version: "3.8"
services:
  cgm-lights:
    ports:
      - "5000:5000"
    build: .
    stop_signal: SIGINT
    volumes:
      - .:/app
    restart: "always"
    environment:
      - FLASK_DEBUG=1
      - PORT=5000
      - LOGLEVEL=DEBUG
