name: Docker Image CI

on:
  push:
    branches: [ "main", "northflank_deploy" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{secrets.DOCKER_USERNAME}}/cgm_smart_lights

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags
        labels: ${{ steps.meta.outputs.labels }}

#  deploy:
    # runs-on: ubuntu-latest
    # needs: build
    # permissions:
    #     contents: read
    #     packages: write

    # steps:
    # - name: Deploy to Northflank
    #   uses: northflank/deploy-to-northflank@v1
    #   with:
    #     northflank-api-key: ${{ secrets.NORTHFLANK_API_KEY }}
    #     project-id: ${{ secrets.NORTHFLANK_PROJECT_ID }}
    #     service-id: ${{ secrets.NORTHFLANK_SERVICE_ID }}
    #     image-path: dellinger/cgm_smart_lights:latest
    #     credentials-id: ${{ secrets.NORTHFLANK_CREDENTIALS_ID }}
