name: Docker Image CI

on:
  push:
    branches: [ "main", "northflank_deploy" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/cgm_smart_lights:$(date +%s)

    - name: Deploy to Northflank
      uses: northflank/deploy-to-northflank@v1
      with:
        northflank-api-key: ${{ secrets.NORTHFLANK_API_KEY }}
        project-id: ${{ env.NORTHFLANK_PROJECT_ID }}
        service-id: ${{ env.NORTHFLANK_SERVICE_ID }}
        image-path: https://hub.docker.com/repository/docker/dellinger/cgm_smart_lights:latest
        credentials-id: ${{ env.NORTHFLANK_CREDENTIALS_ID }}
